### ISSUE TITLE
bullets hit the dirt right in front of the player after playing for 2 days

### ISSUE THREAD

**Issue by commy2** [KoffeinFlummi/AGM#1619]
https://www.youtube.com/watch?v=6jK6De8bEnU

Note the script errot on 1:37

~~Flummi requested logs already.~~ RPT is in video description

**Comment by commy2** [comment]
reminder: `if (_totalTime - time) > 1800 exitWith {0};`

**Comment by esteldunedain** [comment]
The problem was as following: 

- When shooting the first shot after connecting, the code assumed the previous shot was shot at time 0. 
- Consequently, when connecting to a server which has being on for very long (big `time`), the algorithm tried to compute cooling for a long period, which exceeded the run time for non-scheduled environments. 
- The algorithm was then stopped by the engine, generating a wrong return value (nil?), which messed the ballistics.

Now when there is a big interval since the last shot the weapon is assumed completely cooled off without any calculation. The calculation was also tweaked not to fail for intermediate firing intervals.
