### ISSUE TITLE
Add spare barrels to automatic riflemen via script

### ISSUE THREAD

**Issue by esteldunedain** [KoffeinFlummi/AGM#1916]
We automatically give units earplugs if they need them. We could very well do the same with spare barrels, saving a bunch of work on AGM_Compatibility.

**Comment by captainblaffer** [comment]
Please no,

this can be easily added by the mission maker if he so desires. A spare barrel is just as optional as a weapon attachment or different ammo types.

spare barrel is also probably quite heavy, throwing off the weight balance of your loadout.

**Comment by esteldunedain** [comment]
> Then there are also add-ons incompatible with AGM. I don't want my AR soldiers with those ARs to have spare barrels, since they can't use them

Of course that would only be added if the AR has an MG with swapable barrel. 

> spare barrel is also probably quite heavy, throwing off the weight balance of your loadout.

ATM spare barrel are not heavy in AGM; they only weight 0.5 Kg, which is of course to little compared to real life (usually 3 Kg and up for MGs). 

That weight should probably be increased somewhat. A mass of 50 (2.5 Kg) sounds like a better compromise to me.

**Comment by commy2** [comment]
I'd say no, because having it defined in config is a much cleaner aproach. It also won't conflict with loadout scripts.
Earplugs get added by script, because += breaks with inherited classes (like soldier classes) and therefore you can only ever add one item. (Spare barrels for machine gunners and diffusal kits for EODs, ...)
I will change the mass to 50. This way they will no longer fit into uniforms (40),except for ghillies which take 60 for some reason).

**Comment by esteldunedain** [comment]
:+1:
