### ISSUE TITLE
Forcing ragdoll instead of unconcious animations?

### ISSUE THREAD

**Issue by Tachii** [KoffeinFlummi/AGM#1929]
I've found this great thing http://killzonekid.com/arma-scripting-tutorials-forced-ragdoll/

Can u use it instead of unconcious animations maybe? It would be cool

**Comment by kripto202** [comment]
I can see how this could be useful for the lone survivor moments too.

**Comment by BaerMitUmlaut** [comment]
The ragdoll only lasts for a few seconds, I don't think that will work well.

**Comment by Tachii** [comment]
Even if it doesn't last long enough it can be at least used as a transition from normal state to unconsciousness state, because now there is no transition animations fo this, that were in arma 2

**Comment by esteldunedain** [comment]
Sorry, this was already tested by flummi and found not reliable enough. There is currently no ragdoll API (scripting commands) on Arma 3.

**Comment by Tachii** [comment]
Not even reliable as a transition? You can force ragdoll and then play the unconcious animation?

**Comment by esteldunedain** [comment]
> Not even reliable as a transition? You can force ragdoll and then play the unconcious animation?

I don't think so; considering the way that ragdolls are trigger it's hardly surprising.

**Comment by Tachii** [comment]
Well, too bad.

**Comment by KoffeinFlummi** [comment]
To expand a bit on what @esteldunedain said:

There's two issues with this.

One is the way this is achieved. I actually tried to accomplish something similar in the very first version of AGM_Medical (back when the prefix was still BWA3): It creates an invisible object and slams it into the player causing the "run-over-by-car" thing, ragdollizing you. This has a bunch of problems. First of all, you have to disallow damage for a while, because otherwise the collision would hit you. Secondly, you cannot - especially in an MP environment where everything lags around somehow (even local objects, weirdly enough) - reliably ensure that the object actually knocks the player out. While these issues could potentially be overcome, I don't view it as worth the effort without a dedicated ragdoll API by BI.

The second issue is that the ragdoll only lasts for a few seconds, requiring the use of `enableSimulation` to keep the player in place. This is bad for all kinds of reasons, especially in MP. The first versions of AGM_Medical used this to keep the player down and trust me, it had issues.
