### ISSUE TITLE
Player struck - playMoveNow "Incapacitated

### ISSUE THREAD

**Issue by havena** [KoffeinFlummi/AGM#1942]
when i use this animation with 0.95, player struck.

player playMoveNow "Incapacitated";

**Comment by PabstMirror** [comment]
If you need to knock someone out you might want to use 
`[_unit, 99999] call AGM_Medical_fnc_knockOut;`
Otherwise, I don't think there are transitions for that animation, so you would want to use switchMove or use AGM's animation system to apply it:
`[player, "Incapacitated", 2] call AGM_Core_fnc_doAnimation`

Does this problem happen in vanilla ArmA?

**Comment by havena** [comment]
no not in vanilla only with agm.
i dont use medical, so i cant use med knock script

**Comment by commy2** [comment]
Known. Solved in dev.

**Comment by commy2** [comment]
FYI. You should use `switchMove ""` to switch back.
