### ISSUE TITLE
AGM_Logistics objects virtual?

### ISSUE THREAD

**Issue by havena** [KoffeinFlummi/AGM#1957]
hello,

i don't understand why the logistics objects (AGM_JerryCan AGM_SpareTrack AGM_SpareWheel, etc) are virtual ?

Put them in A3 item like other AGM stuff (handcuff, ears etc) would be better and easier ?

Best regards

**Comment by AugustoHA** [comment]
@havena They not make the AGM Logistics an A3 Item because you can't put Any wheel, or Track or JerryCan in your bag, this objects are bigger than your bag. If they change for an item, the people will try carry the wheel in the Bag. ( This is MY THINK; I can be wrong. )

**Comment by BaerMitUmlaut** [comment]
You would not be able to drag them when they're too big to put in your inventory because they would have to be put into a weaponholder to spawn them, and making weaponholders draggable would be very weird (then you could drag dropped weapons and items).

Now say you make a workaround for that, even a single tank track link is very heavy (a German Tiger I tank track link apparently weights above 30kg, I'd imagine modern ones wouldn't be much different), a car wheel simply is too big and a filled Jerry Can is also very heavy. Putting them a backpack is not really feasible, so might as well not make them proper inventory items.

**Comment by havena** [comment]
we can set heavy weight on arma item? for prevent item on backpack.
its not harder to drag a weaponholders than actual script..

**Comment by BaerMitUmlaut** [comment]
If you prevent the item from getting put in a backpack, might as well leave the current solution?

And yes, you can make weaponholders draggable, but then you can drag all weaponholders, those that just contain items (so for example just some magazines lying on the ground) as well.

**Comment by havena** [comment]
Just add condition for drag.
I will check for bakcpack weight.
