### ISSUE TITLE
Boolean Parameters not working anymore e.g. 'AGM_Medical_AllowNonMedics = 0'

### ISSUE THREAD

**Issue by ir0n1e** [KoffeinFlummi/AGM#1963]
All numeric 'AGM_Parameters_Boolean' not working anymore.

**Comment by esteldunedain** [comment]
What are you trying to do exactly?

**Comment by ir0n1e** [comment]
I don't use the modules in the A3 editor. I use the parameters in my *.sqf.
If you set  'AGM_Medical_AllowNonMedics = 0' you get an error in statemants like this: 
'if (AGM_Medical_AllowNonMedics) then {foo};' That's normal.
So, if you look in 'AGM_Medical/config.cpp' you see numeric parameters.

**Comment by bux578** [comment]
Try `true` instead of `1` and `false` instead of `0`

**Comment by esteldunedain** [comment]
Aha, ok. @ir0n1e, we changed how boolean parameters work internally on 0.95.1, because treating them as numbers was very cumbersome.

No boolean parameters become boolean variables upon start, so you should use 

`AGM_Medical_AllowNonMedics = true/false;`

Keep in mind that parameters can be specified on description.ext too, which may o may not be easier for you.

In that case you put them like this:

```
AGM_Parameters_Boolean {
    AGM_Medical_AllowNonMedics = 0; // Parameters are always numbers in the config
};
```

**Comment by ir0n1e** [comment]
kk, thanks.
