### ISSUE TITLE
AGM resting Glitch

### ISSUE THREAD

**Issue by meat147** [KoffeinFlummi/AGM#2050]
I will just leave this here.. :)

https://www.youtube.com/watch?v=N9diDeUXxIk

**Comment by commy2** [comment]
i don't get it. Thats how IK animations in Arma 3 look like. Nothing we can do about that.

**Comment by commy2** [comment]
Just to ilustrate. This is what happens when you vault while standing next to a stone:
![http://i.imgur.com/SrU86M4.jpg](http://i.imgur.com/SrU86M4.jpg)

When resting the weapon you switch between a weaponIK 0 and 1 state, which means that the game tries to allign the weapon aswell as the foots to the surface when resting. This is needed, otherwise the weapon wouldn't be rested on the surface at all.
This will look stupid on steep surfaces, but the same happens with other animations, e.g. vaulting which I showed in the pic.

Again, nothing we can do about it.

**Comment by meat147** [comment]
Ah okay. :) Then it is fine. :) I just saw it.
