### ISSUE TITLE
Can't call AGM_Medical_fnc_knockOut from Arma 3 Editor init line?

### ISSUE THREAD

**Issue by AndrewKopczynski** [KoffeinFlummi/AGM#2106]
I plopped down a unit in the Arma 3 editor and tried to run this code in their init line:

`this setVariable ["AGM_AllowUnconscious", true];   [this, 999999] call AGM_Medical_fnc_knockOut; this setDamage 0.5;`

The unit takes the damage specified, but does not get knocked out. I'm using the code straight from https://github.com/KoffeinFlummi/AGM/wiki/For-Mission-Makers in section 2.11

Is there a different way I'm suppose to be running this to knock out NPCs? It works in-game with the console, but I wanted to use the script for a multiplayer mission so that's not an option.

**Comment by esteldunedain** [comment]
@AndrewKopczynski, I cannot test this ATM, but I think the falling unconscious animation change is failing to register that soon on the mission. Please try:

```sqf
if (local this) then {this spawn {sleep 1; _this setVariable ["AGM_AllowUnconscious", true]; _this setDamage 0.5; [_this, 999999] call AGM_Medical_fnc_knockOut;};};
```

The local is for the knockOut function to only be called once (on the machine that owns the unit, usually the server). The init fields are executed every time a client connects, so otherwise the unit would fall unconscious again every time a new JIP player connects!

**Comment by AndrewKopczynski** [comment]
That works, thanks a bunch!
