### ISSUE TITLE
Moving while changing weapons (and possible other animations)

### ISSUE THREAD

**Issue by a567765** [KoffeinFlummi/AGM#2107]
Now then you start to change from main weapon to AT (for exaple) - your body completely freezes until changing animation is finished. It makes you very vulnerable for enemy fire for a certain amount of time without any means to protect yourself.

Is it possible to remove this forced immobilization for such animations? I don't see any practical reasons why man can't move while changing some light weapons and launchers (rpg7(26), at-4 for exmpl.) But it may stay for "big" tubes like javelin or spiker.

**Comment by brainslush** [comment]
I primarily would like to see this feature for swapping between your rifle and handgun. The problem is that the animations exist but they look a bit weird: https://www.youtube.com/watch?v=The_VrqZWH8 You notice that there is some kind of time jump in the animation. Also i find it extremly annoying that the unit puts the weapon on his back since nowadays it's done this way https://www.youtube.com/watch?v=D10HmlFG_vk&feature=player_detailpage#t=82 using a strip such that your weapon remains on your front.

**Comment by Legolasindar** [comment]
Some transitions
https://www.youtube.com/watch?v=moP0IdZz6zQ
https://www.youtube.com/watch?v=l8la9b7bl7Q

**Comment by jonpas** [comment]
Duplicate of #62
