### ISSUE TITLE
Q: Where did the reworked map go?

### ISSUE THREAD

**Issue by Raspu86** [KoffeinFlummi/AGM#2111]
Better visible heights, contour lines, forests, streets, etc. Where did they go? We had them in BWA3 Realism once.
 It would be nice to have something like this again:
http://i.imgur.com/ibJPWWl.jpg

**Comment by captainblaffer** [comment]
Sounds like you need to press the toggle texture button on the map?

http://i.imgur.com/8dEbxXl.jpg

**Comment by Raspu86** [comment]
Nope, heights, contour lines, forests, streets were a lot more visible/stronger before.

**Comment by captainblaffer** [comment]
When I click that button the map will look just like the one in your picture. White with everything you explain very clearly visible

**Comment by KoffeinFlummi** [comment]
> Better visible heights, contour lines, forests, streets, etc. Where did they go? We had them in BWA3 Realism once.

I don't think we did. Maybe you're thinking of the Navipad?

**Comment by Raspu86** [comment]
That's how it looks like right now: http://i.imgur.com/uSGjVmN.jpg

That's how it could look like:
http://www.lib.utexas.edu/maps/topo/former_yugoslavia/krk-croatia-50k-2185iii-1995.pd
http://www.lib.utexas.edu/maps/topo/laos/txu-pclmaps-oclc-743384338-ban-poung.jpg
http://www.lib.utexas.edu/maps/topo/former_yugoslavia/banovici-bosnia_and_herzegovina-50k-2783i-1996.pdf

**Comment by jonpas** [comment]
I suggest you check out: http://www.armaholic.com/page.php?id=26364

**Comment by Raspu86** [comment]
Turns out you can achieve a lot more realistic and lot more readable map pretty easily. So here we go

http://i.imgur.com/J0FmUpi.jpg
http://i.imgur.com/uK4Oezm.jpg

**Comment by jonpas** [comment]
I do like contour interval dialog.

**Comment by Legolasindar** [comment]
Personally I like to see is the elimination of gray squares that replace those buildings. It is very difficult sometimes, understand that building on the map viewing, if you can have 2 levels, if you have a stone wall or a fence, if a building and nothing else.
The other day, for example, had to identify a football on the map, and it was impossible because the field appeared on the map as a gray rectangle, not the satellite image.
This should include a button to toggle the gray squares. Or just not include them.
I understand that actual maps are similar, but they also have available satellite images.
