### ISSUE TITLE
Explosive system improve

### ISSUE THREAD

**Issue by xPride** [KoffeinFlummi/AGM#2141]
Like this http://www.armaholic.com/page.php?id=28274

**Comment by kripto202** [comment]
agm has most of the functions but it can be improved by:
> can't place bouncing mine in concrete or steel grounds
> make a sound mine

**Comment by ozdeadmeat** [comment]
Looks awesome to me. Needs an ability to group explosives together somehow. Like configuring the Explosive somehow. IE Config one C4 as ID1 and 5 C4 as ID2 and be able to set either of them off with the remote detonator.

**Comment by KoffeinFlummi** [comment]
Since you have put so much effort into this issue your dedication to this is obvious; I am sure we can expect a pull request from you in the next few days.

Alternatively, you could at least put 5 minutes worth of effort into making a request for someone else to spend hours implementing something for you.
