### ISSUE TITLE
Replacing keyboard scheme

### ISSUE THREAD

**Issue by gzhegow** [KoffeinFlummi/AGM#2186]
I like to use Tab to hold the weapon.
But i cant use Tab with AGM for locking the target.
If i use T-button, my hero is clearing glasses :) and not loking targets.

Yes, i can unbind some keys or create new values. But in Arma engine i can add to one key several functions. But here i cant.

**Comment by commy2** [comment]
Problem is that the vanilla keybinds are actually "actions", while we have to work with keyDown events. There are only 20 reserved action key (User Action 1 - 20), but these are useless, because many other mods want to make use of them aswell.
Keys overwriting actions from the base game is a design decission. You should still be able to bind multiple keybinds from AGM to one key.

**Comment by gzhegow** [comment]
Other addons like Task Force Radio allows to use Arma function with mod functions.
RHS allow this too! Rhs framework get user defined keys with actions and display something like this:

RHS Function | Defined key | Game function
---------------------------------------------------------------------
Fold stock | Ctrl + F1 | Set Red Group
Select laser | Ctrl + F2 | Set Blue Group

And it works before stopping group selecting.

**Comment by esteldunedain** [comment]
> Keys overwriting actions from the base game is a design decission.

**Comment by gzhegow** [comment]
Design decission? Fix maybe?
If i want to command my soldiers, i need to replace AGM keys.
I can drop to this page my keyboard layout.
It did taken more than 100 hours of testing.
But what about usability - lets evaluate.
