### ISSUE TITLE
Ability to carry two Main weapons

### ISSUE THREAD

**Issue by Minidou** [KoffeinFlummi/AGM#254]
Is it possible to have the feature to carry two main weapons ? 

Exemple : A breacher can carry one M4A1 and one shotgun in the back for the CQB.

Idea : For that you can try to unlock the AT slot so it will restrict the "Rambo" player who want to use 2 main weapons 1 AT.

**Comment by kripto202** [comment]
I wonder is it possible where you also state the primary as a launcher too.

**Comment by commy2** [comment]
It's not. Everything about the gear system is hard coded. The item has to be a specific type and simulation class to fit in that slot (type 4, simulation RocketLauncher ,iirc ). Changing those values won't let them fit into the primary weapon slot (type 1, simulation Rifle).

Those values are bitmasks, but using 5 will only make one weapon using up both slots and causes more issues, because that behavior which was used for machine guns in A2 is no longer supported in A3. (Weapon duplication or deletion glitches)

**Comment by WastedMike** [comment]
Is there a way to write this into the mod?

http://www.armaholic.com/page.php?id=31062

**Comment by kripto202** [comment]
might want to shift this over to ACE
