### ISSUE TITLE
Locking and Breaching System

### ISSUE THREAD

**Issue by BlackAcidLaser** [KoffeinFlummi/AGM#576]
Give players the ability to lock doors on buildings and subsequently breach them using explosives.

**Comment by Hirntod** [comment]
With the Arma 2 breaching script, you got the opportunity to blow the doors up. But they disappeared instead of open up. How about this?
Btw, in my mind, the fact the doors doesn´t open faster than usual, isn´t bad. While the door´s get open, you throw your Flashbang anyway. It´s just important to let the door open 180°.
It would be awesome if AGM get this feature. Can´t wait for that ;)
